Added German Translation
cuberite/android pull request #12
Opened 2019-02-27 21:31 UTC by mrbesen

Added German Translation
+ Little typo fix at nl-strings

2019-03-01 21:22 UTC, ItsShadowCone requested changes
A few typos, should be an easy fix. A few things where there are probably multiple options, I marked a way that "feels better" to me. If there's anything left to discuss or explain, please point that out.

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="status_missing_filemanager">Kein Dateimanager gefunden: bitte einen Installieren</string>
Shouldn't this be "zu Installieren" (otherwise lowercase "installieren" depending on use)

```suggestion
    <string name="status_missing_filemanager">Kein Dateimanager gefunden: bitte einen zu Installieren</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="notification_cuberite_running">Cuberite Läuft!</string>
```suggestion
    <string name="notification_cuberite_running">Cuberite läuft!</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="installservice_description">Dieser Dienst läd Cuberite herunter, überprüft es und installiert es.</string>
```suggestion
    <string name="installservice_description">Dieser Dienst lädt Cuberite herunter, überprüft es und installiert es.</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="message_shasum_not_matching">Die SHA-1 Summen stimmen nicht überein. Das kann bedeuten, dass jemand versucht sie zu spoofen, es kann sich aber auch nur um einen Fehler handeln. Vers
A typo apart from the factual error: if sha checksums don't match that could mean someone was spoofing the download servers I.e. Messing with the download, but not doing that properly. As any attacker who modifies the content could probably also modify its checksum, it really just checks whether all bits came across properly, so a wording alongside that would be :ok_hand: 

```suggestion
    <string name="message_shasum_not_matching">Die SHA-1 Summen stimmen nicht überein. Das kann bedeuten, dass jemand versucht sie zu spoofen, es kann sich aber auch nur um einen Fehler handeln. Versuchen sie es erneut. Sollte der Fehler weiter auftreten können Sie Cuberite über die Einstellungen manuell installieren</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="title_activity_settings">@string/do_open_settings</string>
I don't think this line is even necessary

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_download_host_summary">Der Server, von welchem Cuberite heruntergeladen wird. Wenn sie eigene Versionen bereitstellen, können Sie diese Einstellung entsprechend anpassen, f
```suggestion
    <string name="settings_download_host_summary">Der Server, von welchem Cuberite heruntergeladen wird. Wenn sie eigene Versionen bereitstellen, können Sie diese Einstellung entsprechend anpassen, für automatische Aktualisierung muss der Server gültige SHA-1 Dateien bereit stellen.</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_install_heading">Installations Optionen</string>
```suggestion
    <string name="settings_install_heading">Installationsoptionen</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_install_update">Cuberite aktuallisieren</string>
```suggestion
    <string name="settings_install_update">Cuberite aktualisieren</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_install_update_explanation">An automatischen Aktualisierungen wird noch gearbeitet. Bis dahin kann über diese Funktion Cuberite aktualisiert werden. Achten Sie drauf, dass
```suggestion
    <string name="settings_install_update_explanation">An automatischen Aktualisierungen wird noch gearbeitet. Bis dahin kann über diese Funktion Cuberite aktualisiert werden. Achten Sie drauf, dass eine Aktualisierung Servereinstellungen überschreiben kann.</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_install_update_binary">Cuberite Programdatei herunterladen und installieren</string>
```suggestion
    <string name="settings_install_update_binary">Cuberite Programmdatei herunterladen und installieren</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_webadmin_explanation">Für kleinere Einstellungen sollte die Webadmin Funktionion genutzt werden. Hier kann Benutzername und Passwort festgeleg werden.</string>
```suggestion
    <string name="settings_webadmin_explanation">Für kleinere Einstellungen sollte die Webadmin Funktionion genutzt werden. Hier können Benutzername und Passwort festgelegt werden.</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_webadmin_not_installed">Vor dem ändern dieser Einstellungen muss Cuberite installiert sein. Sie können es direkt installieren oder diesen Dialog schließen.</string>
```suggestion
    <string name="settings_webadmin_not_installed">Vor dem ändern dieser Einstellungen muss Cuberite installiert werden. Sie können es direkt installieren oder diesen Dialog schließen.</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_webadmin_error">Fehler beim Zugreifen auf die Webadmin Einstellungen.</string>
```suggestion
    <string name="settings_webadmin_error">Fehler beim Zugriff auf die Webadmin Einstellungen.</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_webadmin_success">Fertig! Einstellungen werden nach einem neustart von Cuberite übernommen.</string>
```suggestion
    <string name="settings_webadmin_success">Fertig! Einstellungen werden nach einem Neustart von Cuberite aktiv.</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_authentication_errors_explanation">Auf einigen Geräten funktionieren Mojangs-Authentifizierungs-Server nicht. Das problem ist bekannt, konnte aber ncoh nicht behoben werden
```suggestion
    <string name="settings_authentication_errors_explanation">Auf einigen Geräten funktionieren Mojangs Authentifizierungs-Server nicht. Das Problem ist bekannt, konnte aber noch nicht behoben werden. Wenn Sie beim Verbinden den Fehler \"Failed to authenticate!\" erhalten, könnte diese Einstellung helfen.</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_authentication_toggle">Authentifizierung umschalten.</string>
```suggestion
    <string name="settings_authentication_toggle">Authentifizierung an/abschalten.</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_authentication_toggle_error">Beim Zugreiffen auf die Einstellungen ist ein Fehler aufgetreten.</string>
```suggestion
    <string name="settings_authentication_toggle_error">Beim Zugriff auf die Einstellungen ist ein Fehler aufgetreten.</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_info_debug">Debug information</string>
```suggestion
    <string name="settings_info_debug">Debuginformationen</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_info_libraries">Bibliotheken Dritter</string>
This applies to the following lines as well. "Bibliotheken Dritter" (or the respective "Drittanbieterbibliotheken", "Bibliotheken von Dritten", etc) sound fairly strange and might even be misleading, since even though they're of course third parties, the stress is that we're using open source libraries (plus this is the way software usually goes)

```suggestion
    <string name="settings_info_libraries">Open-Source Bibliotheken</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="pathutils_license">Lizenz der PathUtils Funktionen (genuzt um Datein für die manuelle Installation zu wählen)</string>
```suggestion
    <string name="pathutils_license">Lizenz der PathUtils Funktionen (genutzt um Dateien für die manuelle Installation zu wählen)</string>
```

2019-03-01 21:22 UTC, ItsShadowCone commented on app/src/main/res/values-de/strings.xml
> +    <string name="do_install_cuberite">Installiere Cuberite</string>
```suggestion
    <string name="do_install_cuberite">Cuberite installieren</string>
```

2019-03-02 20:11 UTC, mrbesen commented on app/src/main/res/values-de/strings.xml
> +    <string name="title_activity_settings">@string/do_open_settings</string>
Thats why i removed it.

2019-03-02 20:14 UTC, mrbesen commented
yeah, im native german, but im not that great at this stuff.

2019-03-02 20:16 UTC, mrbesen commented on app/src/main/res/values-de/strings.xml
> +    <string name="title_activity_settings">@string/do_open_settings</string>
I think it is, because in the English strings file it looks like this:
```
 <string name="title_activity_settings">Settings</string>
```

2019-03-03 08:43 UTC, Cl1608Ho commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_info_libraries_explanation">Diese App nutzt Biblioltheken Dritter, hier ist eine Liste aller genutzten Bibliotheken und die zugehörigen Lizenzen.</string>
Don't know if I just missed the submit button for this... 
```suggestion
    <string name="settings_info_libraries_explanation">Diese App nutzt Open-Source Bibliotheken, hier ist eine Liste aller genutzten Bibliotheken und deren jeweilige Lizenzen.</string>
```

2019-03-03 22:07 UTC, ItsShadowCone approved these changes

2019-03-03 22:07 UTC, Cl1608Ho commented
Sorry for the mess!

2019-03-03 22:08 UTC, merged