Rework storage management
cuberite/android pull request #45
Opened 2020-01-04 08:35 UTC by mathiascode

We're now using the app's own external storage folder for server files. This complies with Android 10, and we no longer have to ask for write permission, which is a good idea when we run executables. NOTE: since we can no longer access the external storage, this breaks backwards compatibility with earlier versions of the app, but I think it's a necessary evil.

Support for saving server files on SD cards has been added. Fixes #43.

Crashes related to selecting files from some cloud storage providers have been fixed. An input stream is now opened directly from the file URI, instead of relying on hacky ways to get the full file path for URIs.

2020-01-04 10:26 UTC, ItsShadowCone requested changes

2020-01-04 10:26 UTC, Cl1608Ho commented on app/src/main/java/org/cuberite/android/fragments/SettingsFragment.java
> +                });
I believe we should also copy / move the server dir to the new location if the user explicitly changes the location

2020-02-23 23:04 UTC, mathiascode commented
I will finish this in the near future, but it's currently on the back burner due to work.

2020-03-12 15:57 UTC, mathiascode commented
With the exception of #48, I'm postponing these changes until the storage changes in Android 11 are finalized.

2020-07-17 19:25 UTC, mathiascode commented
Seems like Android 11 will restrict access to /Android/data, effectively killing this idea, so I'm scrapping these changes. Sticking with target API version 28 for as long as possible.

SD card support will be incorporated in another way.

2020-07-17 19:25 UTC, closed without merging