Resolve a few warnings
cuberite/android pull request #51
Opened 2020-04-07 15:32 UTC by mathiascode

- Resolved a couple of warnings across the codebase
- Removed state enums, since the usage of enums is discouraged on Android. We already used integers in ProgressReceiver.

2020-04-07 15:50 UTC, tigerw commented
Now what do they have against enums...

2020-04-15 10:25 UTC, ItsShadowCone requested changes
It appears that since enums are fairly powerful constructs in java (classes, and the values are therefore class instances, support methods and overloading, etc), [someone](https://developer.android.com/topic/performance/reduce-apk-size#remove-enums) [on](https://android.jlelse.eu/android-performance-avoid-using-enum-on-android-326be0794dc3) [the](https://stackoverflow.com/a/26175403) [internet](https://stackoverflow.com/a/29972028) said that they might add a few bytes to your memory footprint and a kilobyte or so to your compiled app before compression.

Since we're talking about java in the first place, this being a fairly small application anyway and we're talking about a single use of an enum here, not more than a hundred, I suggest eating the few bytes for the guarantees and benefits an enum gives you. Namely: static guarantees that values must always be one of the defined values and clearly specifying developer intent in the code.

2020-04-15 13:51 UTC, mathiascode commented
Rebased and changed back to enums.

2020-04-25 16:05 UTC, ItsShadowCone approved these changes

2020-04-25 16:06 UTC, merged